sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 6
  - 7
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g codecov
  - npm install coveralls 
  - npm install
script:
  - npm run ci
after_script:  
  - codecov
  - cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js  